/*
 * Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
 * 
 * On Sun Nov 26 23:37:20 IST 2023
 * 
 */

/* Generation options: */
#ifndef __mkStage_1_h__
#define __mkStage_1_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkStage_1 module */
class MOD_mkStage_1 : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt64> INST_input_1;
  MOD_Reg<tUInt64> INST_input_2;
  MOD_Reg<tUInt8> INST_is_valid;
 
 /* Constructor */
 public:
  MOD_mkStage_1(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUWide PORT_get_stage_1;
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUWide DEF_IF_input_1_BITS_62_TO_52_EQ_0b0_THEN_IF_input__ETC___d45;
  tUWide DEF_IF_IF_input_1_BITS_62_TO_52_EQ_0b0_THEN_IF_inp_ETC___d44;
  tUWide DEF_IF_input_1_BITS_62_TO_52_EQ_0b0_THEN_0b0_ELSE__ETC___d43;
 
 /* Rules */
 public:
 
 /* Methods */
 public:
  void METH_feed(tUInt64 ARG_feed_input_1, tUInt64 ARG_feed_input_2, tUInt8 ARG_feed_is_valid);
  tUInt8 METH_RDY_feed();
  tUWide METH_get_stage_1();
  tUInt8 METH_RDY_get_stage_1();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkStage_1 &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkStage_1 &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkStage_1 &backing);
};

#endif /* ifndef __mkStage_1_h__ */
