/*
 * Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
 * 
 * On Sun Nov 26 23:37:20 IST 2023
 * 
 */

/* Generation options: */
#ifndef __mkTest_Stage_1_h__
#define __mkTest_Stage_1_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"
#include "mkStage_1.h"


/* Class declaration for the mkTest_Stage_1 module */
class MOD_mkTest_Stage_1 : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_mkStage_1 INST_dut;
 
 /* Constructor */
 public:
  MOD_mkTest_Stage_1(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
 
 /* Local definitions */
 private:
  tUWide DEF_dut_get_stage_1____d1;
 
 /* Rules */
 public:
  void RL_rl_stage_1_test();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTest_Stage_1 &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTest_Stage_1 &backing);
  void vcd_submodules(tVCDDumpType dt, unsigned int levels, MOD_mkTest_Stage_1 &backing);
};

#endif /* ifndef __mkTest_Stage_1_h__ */
