/*
 * Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
 * 
 * On Sun Nov 26 23:37:20 IST 2023
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkTest_Stage_1.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkTest_Stage_1::MODEL_mkTest_Stage_1()
{
  mkTest_Stage_1_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkTest_Stage_1()
{
  MODEL_mkTest_Stage_1 *model = new MODEL_mkTest_Stage_1();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkTest_Stage_1 &INST_top = *((MOD_mkTest_Stage_1 *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_rl_stage_1_test;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_rl_stage_1_test;
	 INST_top.INST_dut.METH_RDY_feed();
	 DEF_INST_top_DEF_CAN_FIRE_RL_rl_stage_1_test = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_rl_stage_1_test = DEF_INST_top_DEF_CAN_FIRE_RL_rl_stage_1_test;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_rl_stage_1_test)
	   INST_top.RL_rl_stage_1_test();
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_dut.INST_input_1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_input_2.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_dut.INST_is_valid.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkTest_Stage_1::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkTest_Stage_1_instance = new MOD_mkTest_Stage_1(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkTest_Stage_1_instance->INST_dut.set_clk_0)("CLK");
  (mkTest_Stage_1_instance->set_clk_0)("CLK");
}
void MODEL_mkTest_Stage_1::destroy_model()
{
  delete mkTest_Stage_1_instance;
  mkTest_Stage_1_instance = NULL;
}
void MODEL_mkTest_Stage_1::reset_model(bool asserted)
{
  (mkTest_Stage_1_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkTest_Stage_1::get_instance()
{
  return mkTest_Stage_1_instance;
}

/* Fill in version numbers */
void MODEL_mkTest_Stage_1::get_version(char const **name, char const **build)
{
  *name = "2021.12.1";
  *build = "fd501401";
}

/* Get the model creation time */
time_t MODEL_mkTest_Stage_1::get_creation_time()
{
  
  /* Sun Nov 26 18:07:20 UTC 2023 */
  return 1701022040llu;
}

/* State dumping function */
void MODEL_mkTest_Stage_1::dump_state()
{
  (mkTest_Stage_1_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkTest_Stage_1 & mkTest_Stage_1_backing(tSimStateHdl simHdl)
{
  static MOD_mkTest_Stage_1 *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkTest_Stage_1(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkTest_Stage_1::dump_VCD_defs()
{
  (mkTest_Stage_1_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkTest_Stage_1::dump_VCD(tVCDDumpType dt)
{
  (mkTest_Stage_1_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkTest_Stage_1_backing(sim_hdl));
}
