//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Thu Dec 14 00:57:55 IST 2023
//
//
// Ports:
// Name                         I/O  size props
// RDY_feed                       O     1
// read_output_3                  O    69
// RDY_read_output_3              O     1 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// feed_output_stage_2            I   128 reg
// EN_feed                        I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkStage_3(CLK,
		 RST_N,

		 feed_output_stage_2,
		 EN_feed,
		 RDY_feed,

		 read_output_3,
		 RDY_read_output_3);
  input  CLK;
  input  RST_N;

  // action method feed
  input  [127 : 0] feed_output_stage_2;
  input  EN_feed;
  output RDY_feed;

  // value method read_output_3
  output [68 : 0] read_output_3;
  output RDY_read_output_3;

  // signals for module outputs
  wire [68 : 0] read_output_3;
  wire RDY_feed, RDY_read_output_3;

  // ports of submodule input_fifo
  wire [127 : 0] input_fifo$D_IN, input_fifo$D_OUT;
  wire input_fifo$CLR,
       input_fifo$DEQ,
       input_fifo$EMPTY_N,
       input_fifo$ENQ,
       input_fifo$FULL_N;

  // remaining internal signals
  wire [54 : 0] NEG_sum_temp21__q1,
		signed_mantissa_1___1__h258,
		signed_mantissa_2___1__h263,
		sum_temp__h221;
  wire [53 : 0] get_stage_3_mantissa_sum__h277;
  wire [10 : 0] get_stage_3_exponent_sum__h276;
  wire get_stage_3_sign_sum__h275;

  // action method feed
  assign RDY_feed = input_fifo$FULL_N ;

  // value method read_output_3
  assign read_output_3 =
	     { get_stage_3_sign_sum__h275,
	       get_stage_3_exponent_sum__h276,
	       get_stage_3_mantissa_sum__h277,
	       input_fifo$D_OUT[4] || input_fifo$D_OUT[3],
	       !input_fifo$D_OUT[4] && !input_fifo$D_OUT[3] &&
	       (input_fifo$D_OUT[2] || input_fifo$D_OUT[1]),
	       input_fifo$D_OUT[0] } ;
  assign RDY_read_output_3 = input_fifo$EMPTY_N ;

  // submodule input_fifo
  FIFOL1 #( /*width*/ 32'd128) input_fifo(.RST(RST_N),
					  .CLK(CLK),
					  .D_IN(input_fifo$D_IN),
					  .ENQ(input_fifo$ENQ),
					  .DEQ(input_fifo$DEQ),
					  .CLR(input_fifo$CLR),
					  .D_OUT(input_fifo$D_OUT),
					  .FULL_N(input_fifo$FULL_N),
					  .EMPTY_N(input_fifo$EMPTY_N));

  // submodule input_fifo
  assign input_fifo$D_IN = feed_output_stage_2 ;
  assign input_fifo$ENQ = EN_feed ;
  assign input_fifo$DEQ = input_fifo$EMPTY_N ;
  assign input_fifo$CLR = 1'b0 ;

  // remaining internal signals
  assign NEG_sum_temp21__q1 = -sum_temp__h221 ;
  assign get_stage_3_exponent_sum__h276 =
	     (input_fifo$D_OUT[4] || input_fifo$D_OUT[3] ||
	      input_fifo$D_OUT[2] ||
	      input_fifo$D_OUT[1]) ?
	       11'b11111111111 :
	       input_fifo$D_OUT[125:115] ;
  assign get_stage_3_mantissa_sum__h277 =
	     (input_fifo$D_OUT[4] || input_fifo$D_OUT[3]) ?
	       54'h3FFFFFFFFFFFFF :
	       ((input_fifo$D_OUT[2] || input_fifo$D_OUT[1]) ?
		  54'b0 :
		  (sum_temp__h221[54] ?
		     NEG_sum_temp21__q1[53:0] :
		     sum_temp__h221[53:0])) ;
  assign get_stage_3_sign_sum__h275 =
	     !input_fifo$D_OUT[4] && !input_fifo$D_OUT[3] &&
	     (input_fifo$D_OUT[2] ?
		input_fifo$D_OUT[127] :
		(input_fifo$D_OUT[1] ?
		   input_fifo$D_OUT[126] :
		   sum_temp__h221[54])) ;
  assign signed_mantissa_1___1__h258 = -input_fifo$D_OUT[114:60] ;
  assign signed_mantissa_2___1__h263 = -input_fifo$D_OUT[59:5] ;
  assign sum_temp__h221 =
	     (input_fifo$D_OUT[127] ?
		signed_mantissa_1___1__h258 :
		input_fifo$D_OUT[114:60]) +
	     (input_fifo$D_OUT[126] ?
		signed_mantissa_2___1__h263 :
		input_fifo$D_OUT[59:5]) ;

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (input_fifo$EMPTY_N)
	$display("\n**Stage_3_Output**\nsign_sum:%0b\nexponent_sum:%0b\nmantissa_sum:%0b\n",
		 get_stage_3_sign_sum__h275,
		 get_stage_3_exponent_sum__h276,
		 get_stage_3_mantissa_sum__h277);
  end
  // synopsys translate_on
endmodule  // mkStage_3

