//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Thu Dec 14 00:57:57 IST 2023
//
//
// Ports:
// Name                         I/O  size props
// RDY_feed                       O     1
// read_output                    O    65 reg
// RDY_read_output                O     1 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// feed_input_1                   I    64 reg
// feed_input_2                   I    64 reg
// feed_is_valid                  I     1 reg
// EN_feed                        I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkStage_1(CLK,
		 RST_N,

		 feed_input_1,
		 feed_input_2,
		 feed_is_valid,
		 EN_feed,
		 RDY_feed,

		 read_output,
		 RDY_read_output);
  input  CLK;
  input  RST_N;

  // action method feed
  input  [63 : 0] feed_input_1;
  input  [63 : 0] feed_input_2;
  input  feed_is_valid;
  input  EN_feed;
  output RDY_feed;

  // value method read_output
  output [64 : 0] read_output;
  output RDY_read_output;

  // signals for module outputs
  wire [64 : 0] read_output;
  wire RDY_feed, RDY_read_output;

  // ports of submodule input_1
  wire [63 : 0] input_1$D_IN, input_1$D_OUT;
  wire input_1$CLR, input_1$DEQ, input_1$EMPTY_N, input_1$ENQ, input_1$FULL_N;

  // ports of submodule input_2
  wire [63 : 0] input_2$D_IN, input_2$D_OUT;
  wire input_2$CLR, input_2$DEQ, input_2$EMPTY_N, input_2$ENQ, input_2$FULL_N;

  // ports of submodule is_valid
  wire is_valid$CLR,
       is_valid$DEQ,
       is_valid$D_IN,
       is_valid$D_OUT,
       is_valid$EMPTY_N,
       is_valid$ENQ,
       is_valid$FULL_N;

  // ports of submodule stage_2
  wire [150 : 0] stage_2$feed_output_stage_1;
  wire [127 : 0] stage_2$read_output_2;
  wire stage_2$EN_feed, stage_2$RDY_feed, stage_2$RDY_read_output_2;

  // ports of submodule stage_3
  wire [127 : 0] stage_3$feed_output_stage_2;
  wire [68 : 0] stage_3$read_output_3;
  wire stage_3$EN_feed, stage_3$RDY_feed, stage_3$RDY_read_output_3;

  // ports of submodule stage_4
  wire [68 : 0] stage_4$feed_output_stage_3;
  wire [64 : 0] stage_4$read_output_4;
  wire stage_4$EN_feed, stage_4$RDY_feed, stage_4$RDY_read_output_4;

  // remaining internal signals
  wire [54 : 0] x__h1145, x__h1148;
  wire [10 : 0] _theResult_____1_exponent_input_2__h507,
		_theResult_____3_snd_exponent_input_2__h597,
		_theResult___snd_exponent_input_1__h778,
		output_stage_1___1_exponent_input_1__h1085,
		x__h1140;
  wire IF_input_1_first_BITS_62_TO_52_2_EQ_0b0_3_THEN_ETC___d24;

  // action method feed
  assign RDY_feed = input_1$FULL_N && input_2$FULL_N && is_valid$FULL_N ;

  // value method read_output
  assign read_output = stage_4$read_output_4 ;
  assign RDY_read_output = stage_4$RDY_read_output_4 ;

  // submodule input_1
  FIFOL1 #( /*width*/ 32'd64) input_1(.RST(RST_N),
				      .CLK(CLK),
				      .D_IN(input_1$D_IN),
				      .ENQ(input_1$ENQ),
				      .DEQ(input_1$DEQ),
				      .CLR(input_1$CLR),
				      .D_OUT(input_1$D_OUT),
				      .FULL_N(input_1$FULL_N),
				      .EMPTY_N(input_1$EMPTY_N));

  // submodule input_2
  FIFOL1 #( /*width*/ 32'd64) input_2(.RST(RST_N),
				      .CLK(CLK),
				      .D_IN(input_2$D_IN),
				      .ENQ(input_2$ENQ),
				      .DEQ(input_2$DEQ),
				      .CLR(input_2$CLR),
				      .D_OUT(input_2$D_OUT),
				      .FULL_N(input_2$FULL_N),
				      .EMPTY_N(input_2$EMPTY_N));

  // submodule is_valid
  FIFOL1 #( /*width*/ 32'd1) is_valid(.RST(RST_N),
				      .CLK(CLK),
				      .D_IN(is_valid$D_IN),
				      .ENQ(is_valid$ENQ),
				      .DEQ(is_valid$DEQ),
				      .CLR(is_valid$CLR),
				      .D_OUT(is_valid$D_OUT),
				      .FULL_N(is_valid$FULL_N),
				      .EMPTY_N(is_valid$EMPTY_N));

  // submodule stage_2
  mkStage_2 stage_2(.CLK(CLK),
		    .RST_N(RST_N),
		    .feed_output_stage_1(stage_2$feed_output_stage_1),
		    .EN_feed(stage_2$EN_feed),
		    .RDY_feed(stage_2$RDY_feed),
		    .read_output_2(stage_2$read_output_2),
		    .RDY_read_output_2(stage_2$RDY_read_output_2));

  // submodule stage_3
  mkStage_3 stage_3(.CLK(CLK),
		    .RST_N(RST_N),
		    .feed_output_stage_2(stage_3$feed_output_stage_2),
		    .EN_feed(stage_3$EN_feed),
		    .RDY_feed(stage_3$RDY_feed),
		    .read_output_3(stage_3$read_output_3),
		    .RDY_read_output_3(stage_3$RDY_read_output_3));

  // submodule stage_4
  mkStage_4 stage_4(.CLK(CLK),
		    .RST_N(RST_N),
		    .feed_output_stage_3(stage_4$feed_output_stage_3),
		    .EN_feed(stage_4$EN_feed),
		    .RDY_feed(stage_4$RDY_feed),
		    .read_output_4(stage_4$read_output_4),
		    .RDY_read_output_4(stage_4$RDY_read_output_4));

  // submodule input_1
  assign input_1$D_IN = feed_input_1 ;
  assign input_1$ENQ = EN_feed ;
  assign input_1$DEQ =
	     input_1$EMPTY_N && input_2$EMPTY_N && is_valid$EMPTY_N ;
  assign input_1$CLR = 1'b0 ;

  // submodule input_2
  assign input_2$D_IN = feed_input_2 ;
  assign input_2$ENQ = EN_feed ;
  assign input_2$DEQ =
	     input_1$EMPTY_N && input_2$EMPTY_N && is_valid$EMPTY_N ;
  assign input_2$CLR = 1'b0 ;

  // submodule is_valid
  assign is_valid$D_IN = feed_is_valid ;
  assign is_valid$ENQ = EN_feed ;
  assign is_valid$DEQ =
	     input_1$EMPTY_N && input_2$EMPTY_N && is_valid$EMPTY_N ;
  assign is_valid$CLR = 1'b0 ;

  // submodule stage_2
  assign stage_2$feed_output_stage_1 =
	     { input_1$D_OUT[63],
	       input_2$D_OUT[63],
	       output_stage_1___1_exponent_input_1__h1085,
	       _theResult_____1_exponent_input_2__h507,
	       x__h1140,
	       !IF_input_1_first_BITS_62_TO_52_2_EQ_0b0_3_THEN_ETC___d24,
	       x__h1145,
	       x__h1148,
	       input_1$D_OUT[62:52] == 11'b11111111111 &&
	       input_1$D_OUT[51:0] != 52'b0,
	       input_2$D_OUT[62:52] == 11'b11111111111 &&
	       input_2$D_OUT[51:0] != 52'b0,
	       input_1$D_OUT[62:52] == 11'b11111111111 &&
	       input_1$D_OUT[51:0] == 52'b0,
	       input_2$D_OUT[62:52] == 11'b11111111111 &&
	       input_2$D_OUT[51:0] == 52'b0,
	       is_valid$D_OUT } ;
  assign stage_2$EN_feed =
	     stage_2$RDY_feed && input_1$EMPTY_N && input_2$EMPTY_N &&
	     is_valid$EMPTY_N ;

  // submodule stage_3
  assign stage_3$feed_output_stage_2 = stage_2$read_output_2 ;
  assign stage_3$EN_feed = stage_2$RDY_read_output_2 && stage_3$RDY_feed ;

  // submodule stage_4
  assign stage_4$feed_output_stage_3 = stage_3$read_output_3 ;
  assign stage_4$EN_feed = stage_4$RDY_feed && stage_3$RDY_read_output_3 ;

  // remaining internal signals
  assign IF_input_1_first_BITS_62_TO_52_2_EQ_0b0_3_THEN_ETC___d24 =
	     output_stage_1___1_exponent_input_1__h1085 <
	     _theResult_____1_exponent_input_2__h507 ;
  assign _theResult_____1_exponent_input_2__h507 =
	     (input_2$D_OUT[62:52] == 11'b0) ?
	       _theResult_____3_snd_exponent_input_2__h597 :
	       input_2$D_OUT[62:52] ;
  assign _theResult_____3_snd_exponent_input_2__h597 =
	     (input_2$D_OUT[51:0] == 52'b0) ?
	       input_2$D_OUT[62:52] :
	       11'b00000000001 ;
  assign _theResult___snd_exponent_input_1__h778 =
	     (input_1$D_OUT[51:0] == 52'b0) ?
	       input_1$D_OUT[62:52] :
	       11'b00000000001 ;
  assign output_stage_1___1_exponent_input_1__h1085 =
	     (input_1$D_OUT[62:52] == 11'b0) ?
	       _theResult___snd_exponent_input_1__h778 :
	       input_1$D_OUT[62:52] ;
  assign x__h1140 =
	     IF_input_1_first_BITS_62_TO_52_2_EQ_0b0_3_THEN_ETC___d24 ?
	       _theResult_____1_exponent_input_2__h507 -
	       output_stage_1___1_exponent_input_1__h1085 :
	       output_stage_1___1_exponent_input_1__h1085 -
	       _theResult_____1_exponent_input_2__h507 ;
  assign x__h1145 =
	     { (input_1$D_OUT[62:52] == 11'b0) ? 3'b0 : 3'b001,
	       input_1$D_OUT[51:0] } ;
  assign x__h1148 =
	     { (input_2$D_OUT[62:52] == 11'b0) ? 3'b0 : 3'b001,
	       input_2$D_OUT[51:0] } ;
endmodule  // mkStage_1

